version: '3.8'

services:
  tf2livestats:
    #container_name: 'tf2_live_stats'
    image: ghcr.io/suprovsky/tf2_live_stats:latest
    restart: always
    depends_on:
      - db
      - redis
    ports:
      - '127.0.0.1:3020:3020'
      - '127.0.0.1:3021:3021'
      - '127.0.0.1:3022:3022'
      - '127.0.0.1:3023:3023'
      - '127.0.0.1:9001:9001'
      - '20001:20001/udp'
    env_file: .env
    volumes:
      - tf2livestats_logs:/var/www/tf2_live_stats/log
  db:
    #container_name: 'tf2livestats-db'
    image: mariadb:lts
    restart: always
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
  redis:
    image: redis:7.2
    restart: always
    volumes:
      - redis_data:/data

volumes:
  tf2livestats_logs:
  db_data:
  redis_data:
