---
address: 127.0.0.1
pid: tmp/pids/thin.pid
port: 3020
timeout: 30
wait: 30
log: log/thin.log
max_conns: 1024
servers: 4
require: []

environment: production
max_persistent_conns: 512
daemonize: true
chdir: /var/www/tf2_live_stats/current
